const update = (val, current) => typeof val === "function" ? val(current) : val;

export const createEmailSlice = (set, get) => ({
  emailDeliveryEnabled: false,
  emailAttachmentType: "certificate",
  sharedAttachmentFiles: [],
  emailSettings: {
    service: "gmail",
    senderName: "",
    email: "",
    password: "",
    subject: "Your Certificate is Ready!",
    template: "",
    signature: "",
    smtpHost: "",
    smtpPort: "587",
    smtpSecure: false,
  },
  presets: [],
  selectedMessagePresetId: "",
  newMessagePresetName: "",
  isSavingMessagePreset: false,
  selectedSignaturePresetId: "",
  newSignaturePresetName: "",
  isSavingSignaturePreset: false,
  sendProgress: null,
  skipDuplicates: false,
  setEmailDeliveryEnabled: (emailDeliveryEnabled) => set((s) => ({ emailDeliveryEnabled: update(emailDeliveryEnabled, s.emailDeliveryEnabled) })),
  setEmailAttachmentType: (emailAttachmentType) => set((s) => ({ emailAttachmentType: update(emailAttachmentType, s.emailAttachmentType) })),
  setSharedAttachmentFiles: (sharedAttachmentFiles) => set((s) => ({ sharedAttachmentFiles: update(sharedAttachmentFiles, s.sharedAttachmentFiles) })),
  setEmailSettings: (emailSettings) => set((s) => ({ emailSettings: update(emailSettings, s.emailSettings) })),
  setPresets: (presets) => set((s) => ({ presets: update(presets, s.presets) })),
  setSelectedMessagePresetId: (selectedMessagePresetId) => set((s) => ({ selectedMessagePresetId: update(selectedMessagePresetId, s.selectedMessagePresetId) })),
  setNewMessagePresetName: (newMessagePresetName) => set((s) => ({ newMessagePresetName: update(newMessagePresetName, s.newMessagePresetName) })),
  setIsSavingMessagePreset: (isSavingMessagePreset) => set((s) => ({ isSavingMessagePreset: update(isSavingMessagePreset, s.isSavingMessagePreset) })),
  setSelectedSignaturePresetId: (selectedSignaturePresetId) => set((s) => ({ selectedSignaturePresetId: update(selectedSignaturePresetId, s.selectedSignaturePresetId) })),
  setNewSignaturePresetName: (newSignaturePresetName) => set((s) => ({ newSignaturePresetName: update(newSignaturePresetName, s.newSignaturePresetName) })),
  setIsSavingSignaturePreset: (isSavingSignaturePreset) => set((s) => ({ isSavingSignaturePreset: update(isSavingSignaturePreset, s.isSavingSignaturePreset) })),
  setSendProgress: (sendProgress) => set((s) => ({ sendProgress: update(sendProgress, s.sendProgress) })),
  setSkipDuplicates: (skipDuplicates) => set((s) => ({ skipDuplicates: update(skipDuplicates, s.skipDuplicates) })),
});
