export const createEmailSlice = (set, get) => ({
  emailDeliveryEnabled: false,
  emailAttachmentType: "certificate",
  sharedAttachmentFiles: [],
  emailSettings: {
    service: "gmail",
    senderName: "",
    email: "",
    password: "",
    subject: "Your Certificate is Ready!",
    template: "",
    signature: "",
  },
  presets: [],
  selectedMessagePresetId: "",
  newMessagePresetName: "",
  isSavingMessagePreset: false,
  selectedSignaturePresetId: "",
  newSignaturePresetName: "",
  isSavingSignaturePreset: false,
  sendProgress: null,
  skipDuplicates: false,
  setEmailDeliveryEnabled: (emailDeliveryEnabled) => set({ emailDeliveryEnabled }),
  setEmailAttachmentType: (emailAttachmentType) => set({ emailAttachmentType }),
  setSharedAttachmentFiles: (sharedAttachmentFiles) => set({ sharedAttachmentFiles }),
  setEmailSettings: (emailSettings) => set({ emailSettings }),
  setPresets: (presets) => set({ presets }),
  setSelectedMessagePresetId: (selectedMessagePresetId) => set({ selectedMessagePresetId }),
  setNewMessagePresetName: (newMessagePresetName) => set({ newMessagePresetName }),
  setIsSavingMessagePreset: (isSavingMessagePreset) => set({ isSavingMessagePreset }),
  setSelectedSignaturePresetId: (selectedSignaturePresetId) => set({ selectedSignaturePresetId }),
  setNewSignaturePresetName: (newSignaturePresetName) => set({ newSignaturePresetName }),
  setIsSavingSignaturePreset: (isSavingSignaturePreset) => set({ isSavingSignaturePreset }),
  setSendProgress: (sendProgress) => set({ sendProgress }),
  setSkipDuplicates: (skipDuplicates) => set({ skipDuplicates }),
});
