export const createUiSlice = (set, get) => ({
  theme: typeof window !== "undefined" ? localStorage.getItem("certificate-studio-theme") || "dark" : "dark",
  isLoading: false,
  isSending: false,
  emailSummary: null,
  isManualGenerating: false,
  isCanvaModalOpen: false,
  isCanvaConnected: false,
  currentPath: typeof window !== "undefined" ? window.location.pathname || "/user/login" : "/user/login",
  serverFonts: [],
  lastGenerationInfo: null,
  viewportSize: {
    width: typeof window !== "undefined" ? window.innerWidth : 1600,
    height: typeof window !== "undefined" ? window.innerHeight : 900,
  },
  setTheme: (theme) => set({ theme }),
  setIsLoading: (isLoading) => set({ isLoading }),
  setIsSending: (isSending) => set({ isSending }),
  setEmailSummary: (emailSummary) => set({ emailSummary }),
  setIsManualGenerating: (isManualGenerating) => set({ isManualGenerating }),
  setIsCanvaModalOpen: (isCanvaModalOpen) => set({ isCanvaModalOpen }),
  setIsCanvaConnected: (isCanvaConnected) => set({ isCanvaConnected }),
  setCurrentPath: (currentPath) => set({ currentPath }),
  setServerFonts: (serverFonts) => set({ serverFonts }),
  setLastGenerationInfo: (lastGenerationInfo) => set({ lastGenerationInfo }),
  setViewportSize: (viewportSize) => set({ viewportSize }),
});
